[versions]
gson = "2.10.1"
kotlin = "1.9.23"
kotest = "5.8.0"
dokka = "1.9.20"
nexus-publish-gradle-plugin = "1.3.0"
# The last version compatible with Java 8 is 0.13.2.
reckon-gradle-plugin = "0.13.2"

[plugins]

[libraries]
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gradle-kotlin-dsl-plugins = { module = "org.gradle.kotlin:gradle-kotlin-dsl-plugins", version = "4.0.15" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
nexus-publish-gradle-plugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish-gradle-plugin"}
reckon-gradle-plugin = { module = "org.ajoberstar.reckon:org.ajoberstar.reckon.gradle.plugin", version.ref = "reckon-gradle-plugin" }
